### PR TITLE
Scala3

### LINKED ISSUE #163: Scala 3 Builds

### PR DESCRIPTION
**Pull request by zarthross**
- Fixed formatting where needed for Scala3 
- Changed use of http4s `uri` for scala3
- Made type of implicits explicit.

Fixes #163

### CODE REVIEW

**Review by rossabaker — COMMENTED** [review]
Looks on the right track to me.  Just need a `githubWorkflowGenerate`, perhaps?

This could be relevant on series/8.x for http4s-0.23, but I have no idea how much those branches have diverged.  I'm happy to try to cherry-pick this, unless you want to try retargeting.

**Comment by rossabaker** [comment]
I think everything on this was backported and merged with #216?  And we just need to finish merging it forward?

**Comment by zarthross** [comment]
After resolving conflicts, doesn't look like there is much left in this PR.... sooo i'm going to close it.

**Comment by rossabaker** [comment]
Thanks for the work on this.  I'll try to get 8.x and 9.x releases out the door today so people can start using this on Scala 3.

**Pull request closed without merging**
